<?php

namespace WebDNA\Bundle\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

use WebDNA\Bundle\UserBundle\Entity\ContactData;
use WebDNA\Bundle\UserBundle\Repository\Interfaces\ContactDataRepositoryInterface;

/**
 * ContactDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactDataRepository extends EntityRepository implements ContactDataRepositoryInterface
{
    /**
     * @param ContactData $contactData
     * @return mixed|void
     */
    public function save(ContactData $contactData)
    {
        $this->_em->persist($contactData);

        return $this->_em->flush();
    }
}
