<?php

namespace WebDNA\Bundle\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

use WebDNA\Bundle\AppBundle\Entity\AnalysisProcessOutput;
use WebDNA\Bundle\AppBundle\Repository\Interfaces\AnalysisProcessOutputRepositoryInterface;

/**
 * AnalysisProcessOutputRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnalysisProcessOutputRepository extends EntityRepository implements AnalysisProcessOutputRepositoryInterface
{
    /**
     * @param AnalysisProcessOutput $analysisProcessOutput
     * @return mixed|void
     */
    public function save(AnalysisProcessOutput $analysisProcessOutput)
    {
        $this->_em->persist($analysisProcessOutput);

        return $this->_em->flush();
    }

    /**
     * @param void
     * @return Int
     */
    public function countAll()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT COUNT(apu.id) FROM WebDNAAppBundle:AnalysisProcessOutput apu')
            ->getSingleScalarResult();
    }
}
