<?php

namespace WebDNA\Bundle\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

use WebDNA\Bundle\AppBundle\Entity\AnalysisProcessInput;
use WebDNA\Bundle\AppBundle\Repository\Interfaces\AnalysisProcessInputRepositoryInterface;

/**
 * AnalysisProcessInputRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnalysisProcessInputRepository extends EntityRepository implements AnalysisProcessInputRepositoryInterface
{
    /**
     * @param AnalysisProcessInput $analysisProcessInput
     * @return mixed|void
     */
    public function save(AnalysisProcessInput $analysisProcessInput)
    {
        $this->_em->persist($analysisProcessInput);

        return $this->_em->flush();
    }

    /**
     * @param void
     * @return Int
     */
    public function count()
    {
        return $this->count();
    }

    /**
     * @param void
     * @return Int
     */
    public function countAll()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT COUNT(api.id) FROM WebDNAAppBundle:AnalysisProcessInput api')
            ->getSingleScalarResult();
    }
}
