<?php

namespace WebDNA\Bundle\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

use WebDNA\Bundle\AppBundle\Entity\WebsiteOwnershipConfirmation;
use WebDNA\Bundle\AppBundle\Repository\Interfaces\WebsiteOwnershipConfirmationRepositoryInterface;

/**
 * WebsiteOwnershipConfirmationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebsiteOwnershipConfirmationRepository extends EntityRepository implements WebsiteOwnershipConfirmationRepositoryInterface
{
    /**
     * @param WebsiteOwnershipConfirmation $websiteOwnershipConfirmation
     * @return mixed|void
     */
    public function save(WebsiteOwnershipConfirmation $websiteOwnershipConfirmation)
    {
        $this->_em->persist($websiteOwnershipConfirmation);

        return $this->_em->flush();
    }

    /**
     * @param void
     * @return Int
     */
    public function countAll()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT COUNT(woc.id) FROM WebDNAAppBundle:WebsiteOwnershipConfirmation woc')
            ->getSingleScalarResult();
    }
}
